name: Crumble
description: Adds the new Crumble dimension.
version: 0.0.1
author: Cobalte

main: com.github.cobalte.crumble.Crumble
load: startup

commands:
  crumble:
    description: Sends you to Crumble!
    usage: /crumble
  library:
    description: Sends you to the Dusk Library!
    usage: /library